var mypages = require('./mypages')

exports.getMainPage = function(lista,date,ord)
{
    lista.sort((a, b) =>
    {
        var k = 1;
        if(ord)
            k = -1;
        return k * a.nome.localeCompare(b.nome)
    });
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>About people</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-red w3-centered">
                <h1>Lista de pessoas na base de dados (${lista.length})</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-lime">
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Idade</th>
                        <th>Sexo</th>
                        <th>Cidade</th>
                    </tr>`
    for(let i = 0; i < lista.length; i++)
    {
        pagHtml += `
                    <tr>
                        <td>${lista[i].id}</td>
                        <td>
                        <a href="http://localhost:7777/pessoas/${lista[i].id}">${lista[i].nome}
                        </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                    </tr>
        `
    }
    pagHtml += `
                </table>
            </div>
            <footer class="w3-container w3-red">
                <h5>Generated by pessoas-server: ${date}</h5>
            </footer>
        </div> 
    </body>
</html>
    `
    return pagHtml
}

exports.getPersonPage = function(pessoa,date)
{
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>About people</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-red w3-centered">
                <h1>Nome: ${pessoa.nome}</h1>
            </header>
            <div class="w3-container">`
    pagHtml += `
                <h2>ID: ${pessoa.id}</h2>
                <h2>Cidade: ${pessoa.morada.cidade}</h2>
                <h2>Idade: ${pessoa.idade}</h2>
                <h2>Sexo: ${pessoa.sexo}</h2>
                <h2>Profissao: ${pessoa.profissao}</h2>
    `
    // colocar aqui informação da pessoa recebida
    pagHtml += `
            </div>
            <footer class="w3-container w3-red">
                <h5>Generated by pessoas-server: ${date}</h5>
            </footer>
        </div> 
    </body>
</html>
    `
    return pagHtml
}

exports.getOptionsPage = function(opcoes,date){
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>Menu</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal w3-centered">
                <h1>Menu</h1>
            </header>
            <div class="w3-container">
                <ul class="w3-ul w3-hoverable">
            `
    opcoes.forEach(element => {
        pagHtml+=`
                    <li><a href="${element['link']}">${element['name']}</a></li>`
    });
    pagHtml+= `
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <h5>Generated by pessoas-server: ${date}</h5>
            </footer>
        </div> 
    </body>
</html>
    `
    return pagHtml
}

exports.paginaSexo = function(lista,date)
{
    var sexos = {
        'masculino':0,
        'feminino':0,
        'outro':0
    }
    lista.forEach(element => sexos[element.sexo]++) //encho o dicionario dos sexos
    let totalPsexo = 0
    for (let sex in sexos) {
        if (isNaN(sexos[sex])) {
          delete sexos[sex];
        }
    }
    for(let sex in sexos)
    {
        totalPsexo += sexos[sex] //calculo total de pessoas
    }
    var pagHtml = `
    <!DOCTYPE html>
    <html>
        <head>
            <title>Distribuição de pessoas por sexo</title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="/w3.css">
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-pink w3-centered">
                    <h1>Distribuição de pessoas por sexo</h1>
                </header>
                <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-centered">
                    <tr>
                        <th>Sexo</th>
                        <th>Frequência Absoluta</th>
                        <th>Frequência Relativa</th>
                    </tr>`
        for(let s in sexos){
            pagHtml+= `
                    <tr>
                        <td><a href="http://localhost:7777/pessoas/sexo/${s}">${s}</td>
                        <td>${sexos[s]}</td>
                        <td>${Math.round(sexos[s]/totalPsexo*100)}%</td>
                    </tr>
            `
        }
        pagHtml+= `
                    </table>
                </div>
                <footer class="w3-container w3-pink">
                    <h5>Generated by pessoas-server: ${date}</h5>
                </footer>
            </div> 
        </body>
    </html>
        `
        return pagHtml
}

exports.paginaDesportos = function(lista,date)
{
    var desportos = {}
    lista.forEach(element => {
        if (element.desportos) {
            element.desportos.forEach(desporto=>
                {
                    if(desporto in desportos) desportos[desporto] += 1
                    else desportos[desporto] = 1
                })
        }   
    })
    let totalDesportos = 0
    for (let d in desportos) {
        totalDesportos += desportos[d]
    }
    var pagHtml = `
    <!DOCTYPE html>
    <html>
        <head>
            <title>Distribuição de pessoas por desporto</title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="/w3.css">
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue w3-centered">
                    <h1>Distribuição de pessoas por desporto</h1>
                </header>
                <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-centered">
                    <tr>
                        <th>Desporto</th>
                        <th>Frequência Absoluta</th>
                        <th>Frequência Relativa</th>
                    </tr>`
        for(let sport in desportos){
            pagHtml+= `
                    <tr>
                        <td><a href="http://localhost:7777/pessoas/desporto/${sport}">${sport}</td>
                        <td>${desportos[sport]}</td>
                        <td>${Math.round(desportos[sport]/totalDesportos*100)}%</td>
                    </tr>
            `
        }
        pagHtml+= `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by pessoas-server: ${date}</h5>
                </footer>
            </div> 
        </body>
    </html>
        `
        return pagHtml
}

exports.getProfissoes = function(lista,date)
{
    var profissoes = {}
    lista.forEach(element => {
        if (element.profissao) {
                    if(element.profissao in profissoes) profissoes[element.profissao] += 1
                    else profissoes[element.profissao] = 1
                }
        })
    const sortedprofissoes = Object.entries(profissoes)
        .sort((a, b) => b[1] - a[1])
        .reduce((acc, [key, value]) => ({ ...acc, [key]: value }), {});
    var pagHtml = `
    <!DOCTYPE html>
    <html>
        <head>
            <title>Top 10 profissões</title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="/w3.css">
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-yellow w3-centered">
                    <h1>Top 10 profissões</h1>
                </header>
                <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-centered">
                    <tr>
                        <th>Posição</th>
                        <th>Profissão</th>
                        <th>Pessoas</th>
                    </tr>`
        let i = 1
        for(p in sortedprofissoes){
            pagHtml+= `
                    <tr>
                        <td>${i}</td>
                        <td><a href="http://localhost:7777/pessoas/profissao/${p}">${p}</td>
                        <td>${profissoes[p]}</td>
                    </tr>
            `
            i+=1
            if(i == 11) break;
        }
        pagHtml+= `
                    </table>
                </div>
                <footer class="w3-container w3-yellow">
                    <h5>Generated by pessoas-server: ${date}</h5>
                </footer>
            </div> 
        </body>
    </html>
        `
        return pagHtml
}


exports.paginaUmSexo=function(lista,data,s)
{
    return mypages.getMainPage(lista.filter((p) => p.sexo == s),data)
}

exports.paginaUmDesporto=function(lista,data,d)
{
    return mypages.getMainPage(lista.filter((p) => p.desportos && p.desportos.includes(d)),data)
}

exports.paginaProfissao=function(lista,data,profi)
{
    return mypages.getMainPage(lista.filter((p) => p.profissao == profi),data)
}
